// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/proto/tradingProto.proto
// Protobuf Java Version: 4.29.3

public final class TradingProto {
  private TradingProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      TradingProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TradingDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TradingData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 transactionID = 1;</code>
     * @return The transactionID.
     */
    int getTransactionID();

    /**
     * <code>string date = 2;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 2;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>string time = 3;</code>
     * @return The time.
     */
    java.lang.String getTime();
    /**
     * <code>string time = 3;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>string stockSymbol = 4;</code>
     * @return The stockSymbol.
     */
    java.lang.String getStockSymbol();
    /**
     * <code>string stockSymbol = 4;</code>
     * @return The bytes for stockSymbol.
     */
    com.google.protobuf.ByteString
        getStockSymbolBytes();

    /**
     * <code>string action = 5;</code>
     * @return The action.
     */
    java.lang.String getAction();
    /**
     * <code>string action = 5;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>int32 quantity = 6;</code>
     * @return The quantity.
     */
    int getQuantity();

    /**
     * <code>double price = 7;</code>
     * @return The price.
     */
    double getPrice();

    /**
     * <code>string name = 8;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 8;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string kerberos = 9;</code>
     * @return The kerberos.
     */
    java.lang.String getKerberos();
    /**
     * <code>string kerberos = 9;</code>
     * @return The bytes for kerberos.
     */
    com.google.protobuf.ByteString
        getKerberosBytes();

    /**
     * <code>string comments = 10;</code>
     * @return The comments.
     */
    java.lang.String getComments();
    /**
     * <code>string comments = 10;</code>
     * @return The bytes for comments.
     */
    com.google.protobuf.ByteString
        getCommentsBytes();
  }
  /**
   * Protobuf type {@code TradingData}
   */
  public static final class TradingData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TradingData)
      TradingDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        TradingData.class.getName());
    }
    // Use TradingData.newBuilder() to construct.
    private TradingData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TradingData() {
      date_ = "";
      time_ = "";
      stockSymbol_ = "";
      action_ = "";
      name_ = "";
      kerberos_ = "";
      comments_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TradingProto.internal_static_TradingData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TradingProto.internal_static_TradingData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TradingProto.TradingData.class, TradingProto.TradingData.Builder.class);
    }

    public static final int TRANSACTIONID_FIELD_NUMBER = 1;
    private int transactionID_ = 0;
    /**
     * <code>int32 transactionID = 1;</code>
     * @return The transactionID.
     */
    @java.lang.Override
    public int getTransactionID() {
      return transactionID_;
    }

    public static final int DATE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object date_ = "";
    /**
     * <code>string date = 2;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 2;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object time_ = "";
    /**
     * <code>string time = 3;</code>
     * @return The time.
     */
    @java.lang.Override
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 3;</code>
     * @return The bytes for time.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOCKSYMBOL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stockSymbol_ = "";
    /**
     * <code>string stockSymbol = 4;</code>
     * @return The stockSymbol.
     */
    @java.lang.Override
    public java.lang.String getStockSymbol() {
      java.lang.Object ref = stockSymbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockSymbol_ = s;
        return s;
      }
    }
    /**
     * <code>string stockSymbol = 4;</code>
     * @return The bytes for stockSymbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStockSymbolBytes() {
      java.lang.Object ref = stockSymbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object action_ = "";
    /**
     * <code>string action = 5;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 5;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 6;
    private int quantity_ = 0;
    /**
     * <code>int32 quantity = 6;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }

    public static final int PRICE_FIELD_NUMBER = 7;
    private double price_ = 0D;
    /**
     * <code>double price = 7;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }

    public static final int NAME_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 8;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 8;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KERBEROS_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object kerberos_ = "";
    /**
     * <code>string kerberos = 9;</code>
     * @return The kerberos.
     */
    @java.lang.Override
    public java.lang.String getKerberos() {
      java.lang.Object ref = kerberos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kerberos_ = s;
        return s;
      }
    }
    /**
     * <code>string kerberos = 9;</code>
     * @return The bytes for kerberos.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKerberosBytes() {
      java.lang.Object ref = kerberos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kerberos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENTS_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object comments_ = "";
    /**
     * <code>string comments = 10;</code>
     * @return The comments.
     */
    @java.lang.Override
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      }
    }
    /**
     * <code>string comments = 10;</code>
     * @return The bytes for comments.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (transactionID_ != 0) {
        output.writeInt32(1, transactionID_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, date_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(time_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, time_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stockSymbol_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, stockSymbol_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(action_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, action_);
      }
      if (quantity_ != 0) {
        output.writeInt32(6, quantity_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        output.writeDouble(7, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kerberos_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, kerberos_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(comments_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, comments_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (transactionID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, transactionID_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, date_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(time_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, time_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stockSymbol_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, stockSymbol_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(action_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, action_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, quantity_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kerberos_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, kerberos_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(comments_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, comments_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TradingProto.TradingData)) {
        return super.equals(obj);
      }
      TradingProto.TradingData other = (TradingProto.TradingData) obj;

      if (getTransactionID()
          != other.getTransactionID()) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getTime()
          .equals(other.getTime())) return false;
      if (!getStockSymbol()
          .equals(other.getStockSymbol())) return false;
      if (!getAction()
          .equals(other.getAction())) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getKerberos()
          .equals(other.getKerberos())) return false;
      if (!getComments()
          .equals(other.getComments())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRANSACTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionID();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (37 * hash) + STOCKSYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getStockSymbol().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + KERBEROS_FIELD_NUMBER;
      hash = (53 * hash) + getKerberos().hashCode();
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getComments().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TradingProto.TradingData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TradingProto.TradingData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TradingProto.TradingData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TradingProto.TradingData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TradingProto.TradingData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TradingProto.TradingData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TradingProto.TradingData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static TradingProto.TradingData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static TradingProto.TradingData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static TradingProto.TradingData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TradingProto.TradingData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static TradingProto.TradingData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TradingProto.TradingData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TradingData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TradingData)
        TradingProto.TradingDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TradingProto.internal_static_TradingData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TradingProto.internal_static_TradingData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TradingProto.TradingData.class, TradingProto.TradingData.Builder.class);
      }

      // Construct using TradingProto.TradingData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        transactionID_ = 0;
        date_ = "";
        time_ = "";
        stockSymbol_ = "";
        action_ = "";
        quantity_ = 0;
        price_ = 0D;
        name_ = "";
        kerberos_ = "";
        comments_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TradingProto.internal_static_TradingData_descriptor;
      }

      @java.lang.Override
      public TradingProto.TradingData getDefaultInstanceForType() {
        return TradingProto.TradingData.getDefaultInstance();
      }

      @java.lang.Override
      public TradingProto.TradingData build() {
        TradingProto.TradingData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TradingProto.TradingData buildPartial() {
        TradingProto.TradingData result = new TradingProto.TradingData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(TradingProto.TradingData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.transactionID_ = transactionID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.date_ = date_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.time_ = time_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.stockSymbol_ = stockSymbol_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.action_ = action_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.quantity_ = quantity_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.kerberos_ = kerberos_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.comments_ = comments_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TradingProto.TradingData) {
          return mergeFrom((TradingProto.TradingData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TradingProto.TradingData other) {
        if (other == TradingProto.TradingData.getDefaultInstance()) return this;
        if (other.getTransactionID() != 0) {
          setTransactionID(other.getTransactionID());
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getStockSymbol().isEmpty()) {
          stockSymbol_ = other.stockSymbol_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getKerberos().isEmpty()) {
          kerberos_ = other.kerberos_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (!other.getComments().isEmpty()) {
          comments_ = other.comments_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                transactionID_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                date_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                time_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                stockSymbol_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                action_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                quantity_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 57: {
                price_ = input.readDouble();
                bitField0_ |= 0x00000040;
                break;
              } // case 57
              case 66: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                kerberos_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                comments_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int transactionID_ ;
      /**
       * <code>int32 transactionID = 1;</code>
       * @return The transactionID.
       */
      @java.lang.Override
      public int getTransactionID() {
        return transactionID_;
      }
      /**
       * <code>int32 transactionID = 1;</code>
       * @param value The transactionID to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionID(int value) {

        transactionID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 transactionID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transactionID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 2;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        date_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        date_ = getDefaultInstance().getDate();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        date_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 3;</code>
       * @return The time.
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 3;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 3;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        time_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        time_ = getDefaultInstance().getTime();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string time = 3;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        time_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object stockSymbol_ = "";
      /**
       * <code>string stockSymbol = 4;</code>
       * @return The stockSymbol.
       */
      public java.lang.String getStockSymbol() {
        java.lang.Object ref = stockSymbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stockSymbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stockSymbol = 4;</code>
       * @return The bytes for stockSymbol.
       */
      public com.google.protobuf.ByteString
          getStockSymbolBytes() {
        java.lang.Object ref = stockSymbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockSymbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stockSymbol = 4;</code>
       * @param value The stockSymbol to set.
       * @return This builder for chaining.
       */
      public Builder setStockSymbol(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stockSymbol_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string stockSymbol = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStockSymbol() {
        stockSymbol_ = getDefaultInstance().getStockSymbol();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string stockSymbol = 4;</code>
       * @param value The bytes for stockSymbol to set.
       * @return This builder for chaining.
       */
      public Builder setStockSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stockSymbol_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <code>string action = 5;</code>
       * @return The action.
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string action = 5;</code>
       * @return The bytes for action.
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 5;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        action_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        action_ = getDefaultInstance().getAction();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string action = 5;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        action_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 6;</code>
       * @return The quantity.
       */
      @java.lang.Override
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 6;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {

        quantity_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000020);
        quantity_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 7;</code>
       * @return The price.
       */
      @java.lang.Override
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 7;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {

        price_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000040);
        price_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 8;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 8;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 8;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 8;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object kerberos_ = "";
      /**
       * <code>string kerberos = 9;</code>
       * @return The kerberos.
       */
      public java.lang.String getKerberos() {
        java.lang.Object ref = kerberos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kerberos_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string kerberos = 9;</code>
       * @return The bytes for kerberos.
       */
      public com.google.protobuf.ByteString
          getKerberosBytes() {
        java.lang.Object ref = kerberos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kerberos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string kerberos = 9;</code>
       * @param value The kerberos to set.
       * @return This builder for chaining.
       */
      public Builder setKerberos(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        kerberos_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string kerberos = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearKerberos() {
        kerberos_ = getDefaultInstance().getKerberos();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string kerberos = 9;</code>
       * @param value The bytes for kerberos to set.
       * @return This builder for chaining.
       */
      public Builder setKerberosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        kerberos_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private java.lang.Object comments_ = "";
      /**
       * <code>string comments = 10;</code>
       * @return The comments.
       */
      public java.lang.String getComments() {
        java.lang.Object ref = comments_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          comments_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string comments = 10;</code>
       * @return The bytes for comments.
       */
      public com.google.protobuf.ByteString
          getCommentsBytes() {
        java.lang.Object ref = comments_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comments_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string comments = 10;</code>
       * @param value The comments to set.
       * @return This builder for chaining.
       */
      public Builder setComments(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        comments_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string comments = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearComments() {
        comments_ = getDefaultInstance().getComments();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string comments = 10;</code>
       * @param value The bytes for comments to set.
       * @return This builder for chaining.
       */
      public Builder setCommentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        comments_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TradingData)
    }

    // @@protoc_insertion_point(class_scope:TradingData)
    private static final TradingProto.TradingData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TradingProto.TradingData();
    }

    public static TradingProto.TradingData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TradingData>
        PARSER = new com.google.protobuf.AbstractParser<TradingData>() {
      @java.lang.Override
      public TradingData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TradingData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TradingData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TradingProto.TradingData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradingData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TradingData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&src/main/java/proto/tradingProto.proto" +
      "\"\270\001\n\013TradingData\022\025\n\rtransactionID\030\001 \001(\005\022" +
      "\014\n\004date\030\002 \001(\t\022\014\n\004time\030\003 \001(\t\022\023\n\013stockSymb" +
      "ol\030\004 \001(\t\022\016\n\006action\030\005 \001(\t\022\020\n\010quantity\030\006 \001" +
      "(\005\022\r\n\005price\030\007 \001(\001\022\014\n\004name\030\010 \001(\t\022\020\n\010kerbe" +
      "ros\030\t \001(\t\022\020\n\010comments\030\n \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TradingData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TradingData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TradingData_descriptor,
        new java.lang.String[] { "TransactionID", "Date", "Time", "StockSymbol", "Action", "Quantity", "Price", "Name", "Kerberos", "Comments", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
